
services:
  aigent-frontend:
    build: 
        context: .
        dockerfile: .devcontainer/aigent-frontend/Dockerfile
    volumes:
      - ./aigent-frontend:/workspace
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://backend:8000
      - PORT=3000
    networks:
      - dev-network

  backend:
    build: 
        context: .
        dockerfile: .devcontainer/backend/Dockerfile
    volumes:
      - ./backend:/workspace
      - uploads-data:/app/uploads   # Persistent upload directory
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
      - PORT=8000
      - UPLOAD_FOLDER=/app/uploads  # Set upload folder in environment
    networks:
      - dev-network


# ✅ Make sure the network is explicitly defined here
networks:
  dev-network:
    driver: bridge

volumes:
  uploads-data:  # Define shared volume for uploads
