version: "3.8"
services:
  frontend:
    build: ./aigent-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - aigent-net

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - FLASK_ENV=production
      - UPLOAD_DIR=/app/uploads
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - aigent-net

networks:
  aigent-net:
    driver: bridge
